#!/bin/bash

AWS_ACCESS_KEY_ID=$(iniget /.aws/credentials $AWS_PROFILE aws_access_key_id)
AWS_SECRET_ACCESS_KEY=$(iniget /.aws/credentials $AWS_PROFILE aws_secret_access_key)
AWS_REGION=$(iniget /.aws/config $AWS_PROFILE region)

cat << INFO
=================================================
AWS_PROFILE = $AWS_PROFILE
AWS_REGION  = $AWS_REGION
=================================================
INFO

docker run --rm \
	-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
	-e AWS_REGION=$AWS_REGION \
	amazon/aws-cli $@ 

#::END::
