#!/bin/bash

PROFILE=default
AWS_ACCESS_KEY_ID=$(iniget /.aws/credentials $PROFILE aws_access_key_id)
AWS_SECRET_ACCESS_KEY=$(iniget /.aws/credentials $PROFILE aws_secret_access_key)
AWS_REGION=$(iniget /.aws/config $PROFILE region)

cat << INFO
=================================================
PROFILE=$PROFILE
AWS_REGION=$AWS_REGION
=================================================
INFO

docker run --rm \
	-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
	-e AWS_REGION=$AWS_REGION \
	amazon/aws-cli $@ 

#::END::
