#!/bin/bash

terraform_execute() {
	echo ""
	source terraform.conf 
	local CMD=$1
	local INTERACTIVE=""
	case $CMD in
		console)
			INTERACTIVE="-it"
			;;
	esac
	DATA_DIR=$WORK_DIR/tfdata/data
	PLUGIN_CACHE_DIR=$WORK_DIR/tfdata/plugin-cache
	LOG_DIR=$WORK_DIR/tfdata/log
	[[ ! -f terraform.tfrc ]] && \
		"Config file [terraform.tfrc] doesn't exist. Aborting..." && \
		exit 1
	[[ ! -d $LOG_DIR ]] && mkdir -p $LOG_DIR
	[[ ! -d $DATA_DIR ]] && mkdir -p $DATA_DIR
	[[ ! -d $PLUGIN_CACHE_DIR ]] && mkdir -p $PLUGIN_CACHE_DIR
	echo ""
	docker run \
		$INTERACTIVE \
		--rm \
		-e TF_CLI_CONFIG_FILE=/root/terraform.tfrc \
		-e TF_DATA_DIR=/root/data \
		-e TF_LOG=$LOG_LEVEL \
		-e TF_LOG_PATH=/root/log/terraform.log \
		-v $WORK_DIR:/root/work:rw \
		-v $DATA_DIR:/root/data:rw \
		-v $LOG_DIR:/root/log:rw \
		-v $PLUGIN_CACHE_DIR:/root/plugin-cache:rw \
		-v $AWS_CONFIG_DIR:/.aws:ro \
		-v /var/run/docker.sock:/var/run/docker.sock \
		$TERRAFORM_IMAGE $@
		#-v $DATA_DIR/.terraform:/root/.terraform \
	echo "" 
}

CMD=$1
shift 1
ARGS="$@"

[[ -z ${CMD// /} || $CMD == "help" ]] && CMD="-help" 

case $CMD in
	# Main commands
	init|validate|plan|apply|destroy)			;&
	# All other commans
	console|fmt|force-unlock|get|graph|import|login)	;&
	logout|output|providers|refresh|show|state|taint)	;&
	test|untaint|version|workspace|-help|-version)		;&
	aws)
		terraform_execute $CMD $ARGS
		;;
	*)
		echo "Invalid request: [$CMD]"
		exit 1
		;;
esac

#::END::
