#!/bin/bash

terraform_execute() {
	echo ""
	if [[ -f /etc/terrform.conf ]]; then
		source terraform.conf
	else
		SCRIPT_DIR=$(dirname $(readlink -f $0))
		if [[ -f $SCRIPT_DIR/terraform.conf ]]; then
			source terraform.conf
		else
			echo "Unable to locate terraform.conf under /etc or in current dir [$(pwd)]."
			echo "Aborting..."
			exit 1
		fi
	fi
	local CMD=$1
	local INTERACTIVE=""
	case $CMD in
		apply|destroy|console) INTERACTIVE="-it" ;;
	esac
	readonly WORK_DIR=$(pwd)
	if [[ ! -f .terraform.tfrc ]] ; then
		echo "[.terraform.tfrc] configuration file not found." 
		echo "[.terraform.tfrc] file is required for [terraform] to work."
		read -p "Create basic [.terraform.tfrc] file? [y/N] " -n1 userResponse
		echo ""
		if [[ "${userResponse,,}" == "y" ]]; then
			echo "Creating a default [.terraform.tfrc] file..."
			cat <<- EOF > ./.terraform.tfrc
			plugin_cache_dir   = "/root/plugin-cache"
			disable_checkpoint = true
			EOF
		else
			echo "Without basic [.terraform.tfrc] file [terraform] command doesn't work."
			echo "Aborting..."
			echo ""
			exit 1
		fi
		echo ""
	fi
	docker run \
		$INTERACTIVE \
		--rm \
		-e AWS_PROFILE=$AWS_PROFILE \
		-e TF_CLI_CONFIG_FILE=.terraform.tfrc \
		-e TF_LOG=$LOG_LEVEL \
		-e TF_LOG_PATH=.terraform.log \
		-e PLUGIN_CACHE_DIR=/root/.terraform-plugin-cache \
		-v $WORK_DIR:/root:rw \
		-v $AWS_CONFIG_DIR:/.aws:ro \
		-v /var/run/docker.sock:/var/run/docker.sock \
		$TERRAFORM_IMAGE $@
	echo "" 
}

CMD=$1
shift 1
ARGS="$@"

[[ -z ${CMD// /} || $CMD == "help" ]] && CMD="-help" 

case $CMD in
	# Main commands
	init|validate|plan|apply|destroy)			;&
	# All other commans
	console|fmt|force-unlock|get|graph|import|login)	;&
	logout|output|providers|refresh|show|state|taint)	;&
	test|untaint|version|workspace|-help|-version)		;&
	aws)
		terraform_execute $CMD $ARGS
		;;
	*)
		echo "Invalid request: [$CMD]"
		exit 1
		;;
esac

#::END::
